version: 2.1

orbs:
  jsc-sfdx: jsc/salesforce@1

parameters:
  devhubUsername:
    description: DevHub username for the DevHub org
    type: string
    default: business@lietzau-consulting.de
  devhubInstanceUrl:
    description: DevHub instance URL
    type: string
    default: https://jsc.my.salesforce.com
  powerSuiteDevOrgUsername:
    description: Username for Dev Integration Org for Power Suite development
    type: string
    default: ps-enterprise-dev@lietzau-consulting.de

workflows:
  package_build:
    jobs:
      - jsc-sfdx/scratch_org_test:
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          setupScript: scripts/shell/setup.sh
          runPrettier: true
          runLwcTests: false
          context:
            - salesforce-partner-org
      - jsc-sfdx/build_release_candidate_version:
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          package: PACKAGE_ID
          requireInstallationKey: false
          context:
            - salesforce-partner-org
          filters:
            branches:
              only:
                - /^version/.*/
      - jsc-sfdx/beta_package_deploy:
          name: "power_suite_enterprise_deploy"
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          targetOrgUsername: << pipeline.parameters.powerSuiteDevOrgUsername >>
          devhubJwtKey: SFDX_JWT_KEY
          targetOrgJwtKey: SFDX_JWT_KEY
          devhubConsumerKey: SFDX_CONSUMER_KEY
          targetOrgConsumerKey: SFDX_CONSUMER_KEY_DEV
          package: PACKAGE_ID
          requires:
            - jsc-sfdx/scratch_org_test
          context:
            - salesforce-partner-org
          filters:
            branches:
              only:
                - /^version/.*/
                - /^feature/.*/
                - /^bugfix/.*/
                - /^refactor/.*/
      - approve_package_release:
          type: approval
          requires:
            - power_suite_enterprise_deploy
            - jsc-sfdx/build_release_candidate_version
          filters:
            branches:
              only:
                - /^version/.*/
