version: 2.1

orbs:
  jsc-sfdx: jsc/salesforce@2

parameters:
  devhubUsername:
    description: DevHub username for the DevHub org
    type: string
    default: business@lietzau-consulting.de
  devhubInstanceUrl:
    description: DevHub instance URL
    type: string
    default: https://jsc.my.salesforce.com

jobs:
  uat_beta_package_install:
    description: >
      Installs a beta package build on an integration scratch org for UAT
    docker:
      - image: cimg/openjdk:17.0-node
    parameters:
      setupScript:
        type: string
        default: scripts/shell/uat-setup.sh
      scratchOrgAlias:
        type: string
        default: UatScratch
    steps:
      - checkout
      - jsc-sfdx/install
      - jsc-sfdx/auth:
          consumerKey: SFDX_CONSUMER_KEY
          instanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          setDefault: true
          username: << pipeline.parameters.devhubUsername >>
      - run:
          command: >
            source << parameters.setupScript >> -a << parameters.scratchOrgAlias >> -v << pipeline.parameters.devhubUsername >>
          name: "Prepare Default UAT Scratch Org: << parameters.scratchOrgAlias >>"
      - run:
          command: >
            sf org open -r -o << parameters.scratchOrgAlias >>
          name: "Generate login link for: << parameters.scratchOrgAlias >>"
      - jsc-sfdx/package-install:
          installLatestBuild: true
          devhubUsername: << pipeline.parameters.devhubUsername >>
          targetOrg: << parameters.scratchOrgAlias >>
      - run:
          name: Run all tests in org
          command: |
            set +e
            sf apex run test --target-org << parameters.scratchOrgAlias >> --wait 10 --test-level RunAllTestsInOrg --code-coverage --result-format junit --output-dir test-results/apex
            exitCode=$?
            rm -f test-results/apex/test-result.xml
            rm -f test-results/apex/*.json
            rm -f test-results/apex/*.txt
            exit $exitCode
      - store_test_results:
          path: test-results
  promote_latest_release_candidate:
    description: >
      Promotes the latest package version that was created during the build_release_candidate_version job
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - jsc-sfdx/install
      - jsc-sfdx/auth:
          consumerKey: SFDX_CONSUMER_KEY
          instanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          setDefault: true
          username: << pipeline.parameters.devhubUsername >>
      - jsc-sfdx/package-promote:
          devhubUsername: << pipeline.parameters.devhubUsername >>

workflows:
  package_build:
    jobs:
      - jsc-sfdx/scratch_org_test:
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          setupScript: scripts/shell/setup.sh
          runPrettier: true
          runLwcTests: false
          context:
            - salesforce-partner-org
      - jsc-sfdx/build_release_candidate_version:
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          package: PACKAGE_ID
          requireInstallationKey: false
          context:
            - salesforce-partner-org
          filters:
            branches:
              only:
                - /^version/.*/
      - uat_beta_package_install:
          requires:
            - jsc-sfdx/scratch_org_test
            - jsc-sfdx/build_release_candidate_version
          context:
            - salesforce-partner-org
          filters:
            branches:
              only:
                - /^version/.*/
      - approve_package_release:
          type: approval
          requires:
            - uat_beta_package_install
          filters:
            branches:
              only:
                - /^version/.*/
      - promote_latest_release_candidate:
          requires:
            - approve_package_release
          context:
            - salesforce-partner-org
          filters:
            branches:
              only:
                - /^version/.*/
