version: 2.1

orbs:
  jsc-sfdx: jsc/salesforce@1

parameters:
  devhubUsername:
    description: Production username for the DevHub org (production environment)
    type: string
    default: business@lietzau-consulting.de
  devhubInstanceUrl:
    description: Production instance URL
    type: string
    default: https://jsc.my.salesforce.com

workflows:
  package_build:
    jobs:
      - jsc-sfdx/scratch_org_test:
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          setupScript: scripts/shell/setup.sh
          runPrettier: true
          runLwcTests: false
          context:
            - salesforce-partner-org
      - jsc-sfdx/build_release_candidate_version:
          devhubUsername: << pipeline.parameters.devhubUsername >>
          devhubInstanceUrl: << pipeline.parameters.devhubInstanceUrl >>
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          package: PACKAGE_ID
          requireInstallationKey: false
          context:
            - salesforce-partner-org
          filters:
            branches:
              only:
                - /^version/.*/
